# Site settings
title: CatsLinc Blog
description: CatsLinc-Blog A Elegant template for Jekyll
keywords: CatsLinc, Blogging, Fun
author: loiwu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
